
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox rootContainer;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label1;

	private global::Gtk.SpinButton idInput;

	private global::Gtk.Button stopButton;

	private global::Gtk.Button startButton;

	private global::Gtk.Image videoOut;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.rootContainer = new global::Gtk.VBox();
		this.rootContainer.Name = "rootContainer";
		this.rootContainer.Spacing = 6;
		// Container child rootContainer.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Device");
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.idInput = new global::Gtk.SpinButton(0D, 10D, 1D);
		this.idInput.CanFocus = true;
		this.idInput.Name = "idInput";
		this.idInput.Adjustment.PageIncrement = 10D;
		this.idInput.ClimbRate = 1D;
		this.idInput.Numeric = true;
		this.hbox1.Add(this.idInput);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.idInput]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.stopButton = new global::Gtk.Button();
		this.stopButton.Sensitive = false;
		this.stopButton.CanFocus = true;
		this.stopButton.Name = "stopButton";
		this.stopButton.UseUnderline = true;
		this.stopButton.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.hbox1.Add(this.stopButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.stopButton]));
		w3.PackType = ((global::Gtk.PackType)(1));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.startButton = new global::Gtk.Button();
		this.startButton.CanFocus = true;
		this.startButton.Name = "startButton";
		this.startButton.UseUnderline = true;
		this.startButton.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.hbox1.Add(this.startButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.startButton]));
		w4.PackType = ((global::Gtk.PackType)(1));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.rootContainer.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.rootContainer[this.hbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child rootContainer.Gtk.Box+BoxChild
		this.videoOut = new global::Gtk.Image();
		this.videoOut.Name = "videoOut";
		this.rootContainer.Add(this.videoOut);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.rootContainer[this.videoOut]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.Add(this.rootContainer);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.startButton.Clicked += new global::System.EventHandler(this.OnStart);
		this.stopButton.Clicked += new global::System.EventHandler(this.OnStop);
	}
}
